In [18]:
import pandas as pd 
import numpy as np


In [19]:
df = pd.read_csv('loans_full_schema.csv')

In [20]:
df.head()


emp_title  emp_length state homeownership  annual_income  \
0  global config engineer          3.0    NJ      MORTGAGE        90000.0   
1   warehouse office clerk        10.0    HI          RENT        40000.0   
2                 assembly         3.0    WI          RENT        40000.0   
3         customer service         1.0    PA          RENT        30000.0   
4     security supervisor         10.0    CA          RENT        35000.0   

   verified_income  debt_to_income  annual_income_joint  \
0         Verified           18.01                  NaN   
1     Not Verified            5.04                  NaN   
2  Source Verified           21.15                  NaN   
3     Not Verified           10.16                  NaN   
4         Verified           57.96              57000.0   

  verification_income_joint  debt_to_income_joint  ...  sub_grade  \
0                       NaN                   NaN  ...         C3   
1                       NaN                   NaN  ...         C1   
2                       NaN                   NaN  ...         D1   
3                       NaN                   NaN  ...         A3   
4                  Verified                 37.66  ...         C3   

   issue_month  loan_status  initial_listing_status  disbursement_method  \
0       Mar-18      Current                   whole                 Cash   
1       Feb-18      Current                   whole                 Cash   
2       Feb-18      Current              fractional                 Cash   
3       Jan-18      Current                   whole                 Cash   
4       Mar-18      Current                   whole                 Cash   

    balance  paid_total  paid_principal  paid_interest  paid_late_fees  
0  27015.86     1999.33          984.14        1015.19             0.0  
1   4651.37      499.12          348.63         150.49             0.0  
2   1824.63      281.80          175.37         106.43             0.0  
3  18853.26     3312.89         2746.74         566.15             0.0  
4  21430.15     2324.65         1569.85         754.80             0.0  

[5 rows x 55 columns]

In [6]:
null_counts = df.isnull().sum()
null_counts

emp_title                            833
emp_length                           817
state                                  0
homeownership                          0
annual_income                          0
verified_income                        0
debt_to_income                        24
annual_income_joint                 8505
verification_income_joint           8545
debt_to_income_joint                8505
delinq_2y                              0
months_since_last_delinq            5658
earliest_credit_line                   0
inquiries_last_12m                     0
total_credit_lines                     0
open_credit_lines                      0
total_credit_limit                     0
total_credit_utilized                  0
num_collections_last_12m               0
num_historical_failed_to_pay           0
months_since_90d_late               7715
current_accounts_delinq                0
total_collection_amount_ever           0
current_installment_accounts           0
accounts_opened_

In [ ]:
annual_income_joint                 8505
verification_income_joint           8545
debt_to_income_joint                8505
delinq_2y                              0
months_since_last_delinq            5658

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 201 entries, 37 to 9956
Data columns (total 55 columns):
 #   Column                            Non-Null Count  Dtype  
---  ------                            --------------  -----  
 0   emp_title                         201 non-null    object 
 1   emp_length                        201 non-null    float64
 2   state                             201 non-null    object 
 3   homeownership                     201 non-null    object 
 4   annual_income                     201 non-null    float64
 5   verified_income                   201 non-null    object 
 6   debt_to_income                    201 non-null    float64
 7   annual_income_joint               201 non-null    float64
 8   verification_income_joint         201 non-null    object 
 9   debt_to_income_joint              201 non-null    float64
 10  delinq_2y                         201 non-null    int64  
 11  months_since_last_delinq          201 non-null    float64
 12  earliest_cr

Categorical Columns:

homeownership
verified_income
loan_purpose
application_type
grade
sub_grade
issue_month
loan_status


Continuous Columns:

emp_length
annual_income
debt_to_income
delinq_2y
earliest_credit_line
inquiries_last_12m
total_credit_lines
open_credit_lines
total_credit_limit
total_credit_utilized
num_collections_last_12m
num_historical_failed_to_pay
current_accounts_delinq
total_collection_amount_ever
current_installment_accounts
accounts_opened_24m
months_since_last_credit_inquiry
num_satisfactory_accounts
num_accounts_120d_past_due
num_accounts_30d_past_due
num_active_debit_accounts
total_debit_limit
num_total_cc_accounts
num_open_cc_accounts
num_cc_carrying_balance
num_mort_accounts
account_never_delinq_percent
tax_liens
public_record_bankrupt
loan_amount
term
interest_rate
installment
balance
paid_total
paid_principal
paid_interest
paid_late_fees

Statistical overview:

Two categories it's chi-square test

One numerical- t - test 
Two numerical- corelation

More than 2 categories - anova

1. Null Hypothesis: Interest rate for rent ownership is greater than or equal to mortgage ownership

#The null hypothesis: The interest rate for RENT ownership is less than MORTGAGE ownership.

In [11]:
import pandas as pd
from scipy.stats import t

# Dropping columns with more than 50% null values
threshold = 0.5
columns_to_drop = df.columns[df.isnull().mean() > threshold]
cleaned_data = df.drop(columns=columns_to_drop)

# Extract interest rate data for RENT and MORTGAGE ownership
rent_interest_rate = cleaned_data[cleaned_data['homeownership'] == 'RENT']['interest_rate']
mortgage_interest_rate = cleaned_data[cleaned_data['homeownership'] == 'MORTGAGE']['interest_rate']

# Step 1: Calculate sample means
rent_mean = rent_interest_rate.mean()
mortgage_mean = mortgage_interest_rate.mean()

# Step 2: Calculate sample standard deviations
rent_std = rent_interest_rate.std()
mortgage_std = mortgage_interest_rate.std()

# Step 3: Calculate sample sizes
rent_n = rent_interest_rate.count()
mortgage_n = mortgage_interest_rate.count()

# Step 4: Calculate pooled standard error
pooled_std = ((rent_std**2 / rent_n) + (mortgage_std**2 / mortgage_n))**0.5

# Step 5: Calculate t-statistic
t_stat = (rent_mean - mortgage_mean) / pooled_std

# Step 6: Calculate degrees of freedom
df = rent_n + mortgage_n - 2

# Step 7: Calculate p-value (one-tailed test)
p_value = t.cdf(t_stat, df)

# Display the results
print(f"Rent Mean: {rent_mean:.2f}")
print(f"Mortgage Mean: {mortgage_mean:.2f}")
print(f"Rent Std Dev: {rent_std:.2f}")
print(f"Mortgage Std Dev: {mortgage_std:.2f}")
print(f"T-Statistic: {t_stat:.2f}")
print(f"P-Value: {p_value:.5f}")

# Step 8: Decision at 95% confidence level
alpha = 0.05
if p_value < alpha:
    print("Reject the null hypothesis: The interest rate for RENT ownership is less than MORTGAGE ownership.")
else:
    print("Fail to reject the null hypothesis: No evidence suggests the interest rate for RENT ownership is less than MORTGAGE ownership.")


Rent Mean: 12.92
Mortgage Mean: 12.06
Rent Std Dev: 5.04
Mortgage Std Dev: 4.96
T-Statistic: 8.00
P-Value: 1.00000
Fail to reject the null hypothesis: No evidence suggests the interest rate for RENT ownership is less than MORTGAGE ownership.


2. Hypothesis Testing for Loan Amount Based on Account Type

Problem Statement:
We want to test whether the loan amount for joint accounts is greater than or equal to the loan amount for individual accounts.

Hypotheses:

Null Hypothesis: The mean loan amount for joint accounts is greater than or equal to the mean loan amount for individual accounts.

Alternative Hypothesis: The mean loan amount for joint accounts is less than the mean loan amount for individual accounts.

In [29]:
import pandas as pd
from scipy.stats import ttest_ind, levene



# Debug: Check the unique values in the application_type column
print("Unique values in 'application_type':", df['application_type'].unique())

# Separate loan amounts based on account type
joint_loans = df[df['application_type'].str.lower() == 'joint']['loan_amount']
individual_loans = df[df['application_type'].str.lower() == 'individual']['loan_amount']

# Debug: Check sizes of both groups
print(f"Number of Joint Accounts: {joint_loans.size}")
print(f"Number of Individual Accounts: {individual_loans.size}")

# Proceed only if both groups have sufficient samples
if joint_loans.size > 1 and individual_loans.size > 1:

    # Step 2: Perform the one-tailed t-test
    t_stat, p_value = ttest_ind(joint_loans, individual_loans, alternative='less')
    print(f"T-Statistic: {t_stat}")
    print(f"P-Value: {p_value}")

    # Step 3: Decision
    alpha = 0.05
    if p_value < alpha:
        print("Reject the null hypothesis: The loan amount for joint accounts is less than for individual accounts.")
    else:
        print("Fail to reject the null hypothesis: No evidence suggests the loan amount for joint accounts is less than for individual accounts.")
else:
    print("Insufficient data: One or both groups have less than 2 samples.")



Unique values in 'application_type': ['individual' 'joint']
Number of Joint Accounts: 1495
Number of Individual Accounts: 8505
T-Statistic: 14.338732873791962
P-Value: 1.0
Fail to reject the null hypothesis: No evidence suggests the loan amount for joint accounts is less than for individual accounts.


3. Chi-Square Test: Dependency between grade and homeownership

In [ ]:
import pandas as pd
from scipy.stats import chi2_contingency


# Step 3: Create a contingency table
contingency_table = pd.crosstab(df['grade'], df['homeownership'])
print("Contingency Table:")
print(contingency_table)

# Step 4: Perform the Chi-Square test of independence
chi2_stat, p_value, dof, expected = chi2_contingency(contingency_table)

# Step 5: Display results
print("\nChi-Square Test Results:")
print(f"Chi-Square Statistic: {chi2_stat}")
print(f"P-Value: {p_value}")
print(f"Degrees of Freedom: {dof}")
print("\nExpected Frequencies:")
print(expected)

# Step 6: Hypothesis Decision at 99% Confidence Level
alpha = 0.05  # 95% confidence level
if p_value < alpha:
    print("\nConclusion: Reject the null hypothesis.")
    print("'Grade' and 'Homeownership' are dependent.")
else:
    print("\nConclusion: Fail to reject the null hypothesis.")
    print("No evidence suggests that 'Grade' and 'Homeownership' are dependent.")


Contingency Table:
homeownership  MORTGAGE  OWN  RENT
grade                             
A                  1285  347   827
B                  1499  414  1124
C                  1234  335  1084
D                   587  211   648
E                   148   38   149
F                    32    5    21
G                     4    3     5

Chi-Square Test Results:
Chi-Square Statistic: 76.05710197684729
P-Value: 2.3181235217542355e-11
Degrees of Freedom: 12

Expected Frequencies:
[[1177.6151  332.7027  948.6822]
 [1454.4193  410.9061 1171.6746]
 [1270.5217  358.9509 1023.5274]
 [ 692.4894  195.6438  557.8668]
 [ 160.4315   45.3255  129.243 ]
 [  27.7762    7.8474   22.3764]
 [   5.7468    1.6236    4.6296]]

Conclusion: Reject the null hypothesis.
'Grade' and 'Homeownership' are dependent.


4. Null Hypothesis: OWN homeownership and grades A & B are independent

In [34]:
import pandas as pd
from scipy.stats import chi2_contingency



# Step 2: Filter data for OWN homeownership and grades A & B
filtered_data = df[(df['homeownership'] == 'OWN') & (df['grade'].isin(['A', 'B']))]

# Step 3: Create a contingency table
contingency_table = pd.crosstab(filtered_data['grade'], filtered_data['homeownership'])
print("Contingency Table:")
print(contingency_table)

# Step 4: Perform the Chi-Square test
chi2_stat, p_value, dof, expected = chi2_contingency(contingency_table)

# Step 5: Display results
print("\nChi-Square Test Results:")
print(f"Chi-Square Statistic: {chi2_stat}")
print(f"P-Value: {p_value}")
print(f"Degrees of Freedom: {dof}")
print("\nExpected Frequencies:")
print(expected)

# Step 6: Decision
alpha = 0.05  # 95% confidence level
if p_value < alpha:
    print("\nConclusion: Reject the null hypothesis.")
    print("'OWN' homeownership and grades (A & B) are dependent.")
else:
    print("\nConclusion: Fail to reject the null hypothesis.")
    print("No evidence suggests 'OWN' homeownership and grades (A & B) are dependent.")


Contingency Table:
homeownership  OWN
grade             
A              347
B              414

Chi-Square Test Results:
Chi-Square Statistic: 0.0
P-Value: 1.0
Degrees of Freedom: 0

Expected Frequencies:
[[347.]
 [414.]]

Conclusion: Fail to reject the null hypothesis.
No evidence suggests 'OWN' homeownership and grades (A & B) are dependent.


5. ANOVA Test: Loan amount across grades

In [35]:
import pandas as pd
from scipy.stats import f_oneway



# Step 2: Check if required columns exist
if 'grade' not in df.columns or 'loan_amount' not in df.columns:
    raise ValueError("Required columns 'grade' or 'loan_amount' are missing.")

# Step 3: Prepare data for ANOVA
# Group loan_amount by grade
groups = [group['loan_amount'].values for name, group in df.groupby('grade')]

# Step 4: Perform ANOVA
f_stat, p_value = f_oneway(*groups)

# Step 5: Display results
print("ANOVA Test Results:")
print(f"F-Statistic: {f_stat}")
print(f"P-Value: {p_value}")

# Step 6: Decision
alpha = 0.05  # 95% confidence level
if p_value < alpha:
    print("\nConclusion: Reject the null hypothesis.")
    print("The means of loan amounts differ significantly across grades.")
else:
    print("\nConclusion: Fail to reject the null hypothesis.")
    print("No evidence suggests that loan amounts differ across grades.")


ANOVA Test Results:
F-Statistic: 11.064165402506582
P-Value: 2.4777631613342448e-12

Conclusion: Reject the null hypothesis.
The means of loan amounts differ significantly across grades.
